"""Write source.js so the web page shows the exact, tested source files.

    python3 embed.py          # regenerate
    python3 embed.py --check  # fail if source.js is out of date
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
FILES = ["src/Code.gs", "src/parseShift.js", "test/parseShift.test.js", "test/createWorkSchedule.test.js"]

text = "// Generated by embed.py. Do not edit by hand.\nwindow.CALENDAR_SOURCE = " + json.dumps(
    {f: (HERE / f).read_text() for f in FILES}, indent=1) + ";\n"
target = HERE / "source.js"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != text:
        sys.exit("calendar-sync: source.js out of date; run python3 embed.py")
    print("calendar-sync: source.js up to date")
else:
    target.write_text(text)
