"""Convert phone launch prices to constant 2025 dollars with BLS CPI-U and write
results.json / results.js for the web page.

    python3 analyze.py          # regenerate results
    python3 analyze.py --check  # fail if results are out of date with the data

Standard library only.

Two price columns are kept on purpose:
  price_full      what the phone cost outright (unlocked / no-contract / retail)
  price_contract  the headline price with a two-year carrier contract (2007-2015)
Every headline number uses price_full. Mixing the two makes the 2016 end of
carrier subsidies look like a price shock that never happened.
"""
import csv
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
BASE_YEAR = 2025


def num(s):
    return float(s) if s.strip() else None


def load():
    with open(HERE / "data/cpi_u_annual.csv", newline="") as f:
        cpi = {int(r["year"]): float(r["cpi_u"]) for r in csv.DictReader(f)}
    with open(HERE / "data/phones.csv", newline="") as f:
        phones = list(csv.DictReader(f))
    return cpi, phones


def to_base_year(price, year, cpi):
    return None if price is None else round(price * cpi[BASE_YEAR] / cpi[year], 2)


def pct_change(new, old):
    return round((new - old) * 100 / old, 1)


def run():
    cpi, raw = load()
    phones = []
    for r in raw:
        year = int(r["year"])
        full, contract = num(r["price_full"]), num(r["price_contract"])
        assert full is not None or contract is not None, r["phone"]
        phones.append({
            "phone": r["phone"],
            "maker": r["maker"],
            "year": year,
            "category": r["category"],
            "base_storage_gb": int(r["base_storage_gb"]) if r["base_storage_gb"] else None,
            "price_full": full,
            "price_contract": contract,
            "cpi_factor": round(cpi[BASE_YEAR] / cpi[year], 4),
            "real_full": to_base_year(full, year, cpi),
            "real_contract": to_base_year(contract, year, cpi),
            "confidence": r["confidence"],
            "note": r["note"],
            "source": r["source"],
        })

    by_name = {p["phone"]: p for p in phones}
    iphones = sorted((p for p in phones if p["category"] == "iphone"), key=lambda p: p["year"])
    first, latest = iphones[0], iphones[-1]
    s6, i7 = by_name["Apple iPhone 6S"], by_name["Apple iPhone 7"]
    dynatac = by_name["Motorola DynaTAC 8000X"]
    full_priced = [p for p in phones if p["real_full"] is not None]

    summary = {
        "base_year": BASE_YEAR,
        "phones": len(phones),
        "phones_with_full_price": len(full_priced),
        "year_range": [min(p["year"] for p in phones), max(p["year"] for p in phones)],
        "dynatac_real": dynatac["real_full"],
        "dynatac_vs_latest_iphone": round(dynatac["real_full"] / latest["price_full"], 1),
        "iphone_first": {"phone": first["phone"], "year": first["year"],
                         "nominal": first["price_full"], "real": first["real_full"]},
        "iphone_latest": {"phone": latest["phone"], "year": latest["year"],
                          "nominal": latest["price_full"], "real": latest["real_full"]},
        "iphone_nominal_change_pct": pct_change(latest["price_full"], first["price_full"]),
        "cpi_change_pct": pct_change(cpi[latest["year"]], cpi[first["year"]]),
        "iphone_real_change_pct": pct_change(latest["real_full"], first["real_full"]),
        # The 2016 "price jump" depends entirely on which price column you compare.
        "subsidy_artifact": {
            "contract_6s_to_full_7_pct": pct_change(i7["price_full"], s6["price_contract"]),
            "full_6s_to_full_7_pct": pct_change(i7["price_full"], s6["price_full"]),
        },
        "iphone_real_per_gb": {
            "first": round(first["real_full"] / first["base_storage_gb"], 2),
            "latest": round(latest["real_full"] / latest["base_storage_gb"], 2),
        },
        "iphone_real_range": [min(p["real_full"] for p in iphones), max(p["real_full"] for p in iphones)],
        "iphone_real_peak": max(iphones, key=lambda p: p["real_full"])["phone"],
        "top_real": [p["phone"] for p in sorted(full_priced, key=lambda p: -p["real_full"])[:10]],
        "cpi_base": cpi[BASE_YEAR],
    }
    return {"summary": summary, "phones": phones, "cpi": cpi}


def main():
    out = run()
    json_text = json.dumps(out, indent=2) + "\n"
    js_text = "// Generated by analyze.py. Do not edit by hand.\nwindow.PHONES = " + json.dumps(out) + ";\n"

    targets = {HERE / "results.json": json_text, HERE / "results.js": js_text}
    if "--check" in sys.argv:
        stale = [p.name for p, text in targets.items() if not p.exists() or p.read_text() != text]
        if stale:
            sys.exit(f"phone-prices: {', '.join(stale)} out of date; run python3 analyze.py")
        print("phone-prices: results up to date")
        return
    for path, text in targets.items():
        path.write_text(text)
    print(json.dumps(out["summary"], indent=2))


if __name__ == "__main__":
    main()
